#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# fetch repository as zip archive. default is "false"
#shallow_clone: true

# set clone depth
clone_depth: 3

# environment variables
environment:
#  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  MINGW_DIR: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0

# scripts that run after cloning repository
install:
  - set PATH=%MINGW_DIR%;%PATH%
#  - choco install -y msys2 
  - C:\msys64\usr\bin\bash -l -c "pacman -Sy mingw32/mingw-w64-i686-libmariadbclient mingw32/mingw-w64-i686-boost 2>&1"
  - mkdir build
  - cd build
  - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
  - cmake --build .
