os: Visual Studio 2015

configuration:
  - Release

branches:
  # whitelist
  only:
    - master

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

#clone_depth: 3
#shallow_clone: true

init:
  - git config --global core.autocrlf true
  - set PATH=%MINGW_DIR%;%PATH%
#  - cmd: mkdir build
#  - cmd: cd build
  - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
  - cmake --build .
