sudo: required
language:
  - cpp
os:
  - windows

script:
#  - choco install cmake
  - cmake --version
  - mkdir build
  - cd build
  - cmake -G 'MinGW Makefiles' -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
  - cmake --build .
