#
# Configuration
#
language: cpp
dist: xenial

#
# Build Dependencies
#
before_script:
- mkdir build
- cd build

#
# Build Matrix
#
matrix:
  include:

  #
  # Build Release
  #
  - os: linux

    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - libboost-all-dev
          - libmariadb-client-lgpl-dev
          - libmysqlclient-dev

    compiler: gcc
    
    script:
      - cmake -DCI_BUILD:BOOL=ON -DCOVERAGE:BOOL=OFF -DCMAKE_BUILD_TYPE=Release ..
      - make

  #
  # Build Debug
  #
  - os: linux

    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - libboost-all-dev
          - libmariadb-client-lgpl-dev
          - libmysqlclient-dev

    compiler: gcc
    
    script:
      - cmake -DCI_BUILD:BOOL=ON -DCOVERAGE:BOOL=OFF -DCMAKE_BUILD_TYPE=Debug ..
      - make
