dist: xenial
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-all-dev
      - libmariadb-client-lgpl-dev
      - libmysqlclient-dev
before_install:
  - pip install --user cpp-coveralls
before_script:
#  - export CC=gcc-8
#  - export CXX=g++-8
script:
  - mkdir build
  - cd build
  - cmake -DCI_BUILD:BOOL=ON -DCOVERAGE:BOOL=ON ..
  - make
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
