dist: xenial
language:
  - cpp
#compiler:
#  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - libboost-all-dev
      - libmariadb-client-lgpl-dev
      - libmysqlclient-dev

before_script:
  - export CC=gcc-8
  - export CXX=g++-8

script:
  - mkdir build
  - cd build
  - cmake -DCI_BUILD:BOOL=ON ..
  - make
