dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    packages:
#      - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script:
  # Check versions of gcc, g++ and cmake
  #- gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - make
