sudo: required
language:
  - cpp
os:
  - windows

script:
  - choco install -y msys2
  - C:\tools\msys64\usr\bin\bash -l -c "pacman -V"
  - cmake --version
  - mkdir build
  - cd build
  - cmake -G 'MinGW Makefiles' -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
  - cmake --build .
